/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/start/start" |
       "/pages/about/about" |
       "/pages/feedback/feedback" |
       "/pages/mall-login/mall-login" |
       "/pages/order-system-home/order-system-home" |
       "/pages/personal/personal-edit" |
       "/pages/personal/personal" |
       "/pages/service-added/service-added" |
       "/pages/video-course/video-course" |
       "/pages/order-system/address/address-add" |
       "/pages/order-system/address/address-list" |
       "/pages/order-system/cart/cart" |
       "/pages/order-system/category/category" |
       "/pages/order-system/goods-detail/goods-detail" |
       "/pages/order-system/goods-search-list/goods-search-list" |
       "/pages/order-system/order/confirm-order" |
       "/pages/order-system/order/order-detail" |
       "/pages/order-system/order/order-list" |
       "/pages/order-system/order-person/change-password" |
       "/pages/order-system/order-person/order-person" |
       "/pages/order-system/order-person/order-personal-edit" |
       "/pages/order-system/performance-list/performance-list" |
       "/pages/order-system/register/register";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/order-system/category/category" | "/pages/order-system/cart/cart" | "/pages/order-system/order-person/order-person"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
