/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/about/about" |
       "/pages/feedback/feedback" |
       "/pages/member/member-audit" |
       "/pages/member/member-combo-list" |
       "/pages/member/member-combo-log" |
       "/pages/member/member-combo-qr" |
       "/pages/member/member-purchase" |
       "/pages/personal/personal-edit" |
       "/pages/personal/personal" |
       "/pages/shop/shop-combo-check" |
       "/pages/shop/shop-combo-log" |
       "/pages/shop/shop-combo" |
       "/pages/shop/shop-edit" |
       "/pages/shop/shop-member-list" |
       "/pages/shop/shop" |
       "/pages/shop-info/shop-info" |
       "/pages/video-course/video-course";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/video-course/video-course" | "/pages/personal/personal"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
